{
 "title": "Race stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Incident Points",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT d.name, AVG(session_incidents.total_incident_points) AS avg_incident_points\r\nFROM (\r\n    SELECT i.driver_id, i.session_id, SUM(i.incident_points) AS total_incident_points\r\n    FROM race_stats.incidents i\r\n    GROUP BY i.driver_id, i.session_id\r\n) session_incidents\r\nJOIN race_stats.drivers d ON session_incidents.driver_id = d.id\r\nGROUP BY d.name\r\nORDER BY avg_incident_points DESC;\r\n"
    }
   ]
  },
  {
   "title": "Top 3 Car To Car Collision incidents",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT d.name, COUNT(*) AS incident_count\r\nFROM race_stats.incidents i\r\nJOIN race_stats.drivers d ON i.driver_id = d.id\r\nWHERE i.incident_type = 'CarToCarCollision'\r\nGROUP BY d.name\r\nORDER BY incident_count DESC\r\nLIMIT 3;"
    }
   ]
  },
  {
   "title": "Top 5 Track limits per race",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "WITH RankedIncidents AS (\r\n    SELECT\r\n        d.name,\r\n        i.session_id,\r\n        COUNT(*) AS incident_count,\r\n        ROW_NUMBER() OVER (PARTITION BY d.name ORDER BY COUNT(*) DESC) AS rank\r\n    FROM race_stats.incidents i\r\n    JOIN race_stats.drivers d ON i.driver_id = d.id\r\n    WHERE i.incident_type = 'NotServingPenalty'\r\n    GROUP BY d.name, i.session_id\r\n)\r\nSELECT name, incident_count\r\nFROM RankedIncidents\r\nWHERE rank = 1\r\nORDER BY incident_count DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Total amount of laps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT COUNT(*) FROM race_stats.laps LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Points",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT d.name, AVG(r.class_position) AS avg_class_position\r\nFROM race_stats.results r\r\nJOIN race_stats.drivers d ON r.driver_id = d.id\r\nGROUP BY d.name\r\nORDER BY avg_class_position DESC"
    }
   ]
  },
  {
   "title": "Most used Car",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    cars.name AS car_name,\r\n    COUNT(results.car_id) AS usage_count\r\nFROM\r\n    race_stats.results AS results\r\nJOIN\r\n    r3e_content.cars AS cars\r\nON\r\n    results.car_id = cars.id\r\nGROUP BY\r\n    cars.name\r\nORDER BY\r\n    usage_count DESC"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    manufacturers.name AS manufacturer_name,\r\n    COUNT(results.car_id) AS usage_count\r\nFROM\r\n    race_stats.results AS results\r\nJOIN\r\n    r3e_content.cars AS cars\r\nON\r\n    results.car_id = cars.id\r\nJOIN\r\n    r3e_content.manufacturers AS manufacturers\r\nON\r\n    cars.manufacturer_id = manufacturers.id\r\nGROUP BY\r\n    manufacturers.name\r\nORDER BY\r\n    usage_count DESC;\r\n"
    }
   ]
  }
 ]
}