{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Incident Points",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    d.name AS driver_name,\r\n    AVG(session_incidents.total_incident_points) AS avg_incident_points\r\nFROM (\r\n    SELECT\r\n        i.driver_id,\r\n        i.session_id,\r\n        SUM(i.incident_points) AS total_incident_points\r\n    FROM race_stats.incidents i\r\n    JOIN race_stats.sessions s\r\n        ON s.id = i.session_id\r\n    JOIN race_stats.events e\r\n        ON e.id = s.event_id\r\n    WHERE\r\n        e.event_date BETWEEN $__timeFrom() AND $__timeTo()\r\n    GROUP BY\r\n        i.driver_id,\r\n        i.session_id\r\n) AS session_incidents\r\nJOIN race_stats.drivers d\r\n    ON session_incidents.driver_id = d.id\r\nGROUP BY\r\n    d.name\r\nORDER BY\r\n    avg_incident_points DESC;"
    }
   ]
  },
  {
   "title": "Top 3 Car To Car Collision incidents",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    d.name AS driver_name,\r\n    COUNT(*) AS incident_count\r\nFROM race_stats.incidents i\r\nJOIN race_stats.sessions s\r\n    ON s.id = i.session_id\r\nJOIN race_stats.events e\r\n    ON e.id = s.event_id\r\nJOIN race_stats.drivers d\r\n    ON i.driver_id = d.id\r\nWHERE\r\n    i.incident_type = 'CarToCarCollision'\r\n    AND e.event_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n    d.name\r\nORDER BY\r\n    incident_count DESC\r\nLIMIT 3;"
    }
   ]
  },
  {
   "title": "Average Race Position",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    d.name AS driver_name,\r\n    AVG(r.class_position) AS avg_class_position\r\nFROM race_stats.results r\r\nJOIN race_stats.sessions s\r\n    ON s.id = r.session_id\r\nJOIN race_stats.events e\r\n    ON e.id = s.event_id\r\nJOIN race_stats.drivers d\r\n    ON r.driver_id = d.id\r\nWHERE\r\n    e.event_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n    d.name\r\nORDER BY\r\n    avg_class_position ASC;"
    }
   ]
  },
  {
   "title": "Total amount of laps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    COUNT(*) AS lap_count\r\nFROM race_stats.laps l\r\nJOIN race_stats.sessions s\r\n    ON s.id = l.session_id\r\nJOIN race_stats.events e\r\n    ON e.id = s.event_id\r\nWHERE\r\n    e.event_date BETWEEN $__timeFrom() AND $__timeTo();"
    }
   ]
  },
  {
   "title": "Most used Car",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    cars.name AS car_name,\r\n    COUNT(results.car_id) AS usage_count\r\nFROM\r\n    race_stats.results AS results\r\nJOIN\r\n    race_stats.sessions AS sessions\r\n        ON sessions.id = results.session_id\r\nJOIN\r\n    race_stats.events AS events\r\n        ON events.id = sessions.event_id\r\nJOIN\r\n    r3e_content.cars AS cars\r\n        ON results.car_id = cars.id\r\nWHERE\r\n    events.event_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n    cars.name\r\nORDER BY\r\n    usage_count DESC;"
    }
   ]
  },
  {
   "title": "Most used Manufacturer",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    manufacturers.name AS manufacturer_name,\r\n    COUNT(results.car_id) AS usage_count\r\nFROM\r\n    race_stats.results AS results\r\nJOIN\r\n    race_stats.sessions AS sessions\r\n        ON sessions.id = results.session_id\r\nJOIN\r\n    race_stats.events AS events\r\n        ON events.id = sessions.event_id\r\nJOIN\r\n    r3e_content.cars AS cars\r\n        ON results.car_id = cars.id\r\nJOIN\r\n    r3e_content.manufacturers AS manufacturers\r\n        ON cars.manufacturer_id = manufacturers.id\r\nWHERE\r\n    events.event_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n    manufacturers.name\r\nORDER BY\r\n    usage_count DESC;"
    }
   ]
  },
  {
   "title": "Tracks",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    tracks.name AS track_name,\r\n    COUNT(results.id) AS usage_count\r\nFROM\r\n    race_stats.results AS results\r\nJOIN\r\n    race_stats.sessions AS sessions\r\n        ON sessions.id = results.session_id\r\nJOIN\r\n    race_stats.events AS events\r\n        ON events.id = sessions.event_id\r\nJOIN\r\n    r3e_content.tracks AS tracks\r\n        ON events.track_id = tracks.id\r\nWHERE\r\n    events.event_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n    tracks.name\r\nORDER BY\r\n    usage_count DESC;"
    }
   ]
  },
  {
   "title": "Race events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "r3e_racing",
     "rawSql": "SELECT\r\n    COUNT(*) AS event_count\r\nFROM race_stats.events e\r\nWHERE\r\n    e.event_date BETWEEN $__timeFrom() AND $__timeTo();"
    }
   ]
  }
 ]
}