// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R3EServerRaceResult.Data;

#nullable disable

namespace R3EServerRaceResult.Data.Migrations.R3EContent
{
    [DbContext(typeof(R3EContentDbContext))]
    partial class R3EContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("r3e_content")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_cars_class_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_cars_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_cars_manufacturer_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_cars_name");

                    b.ToTable("cars", "r3e_content");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.CarClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_car_classes_name");

                    b.ToTable("car_classes", "r3e_content");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxVehicles")
                        .HasColumnType("integer")
                        .HasColumnName("max_vehicles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_layouts_track_id");

                    b.ToTable("layouts", "r3e_content");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Livery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_liveries_car_id");

                    b.ToTable("liveries", "r3e_content");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_manufacturers_name");

                    b.ToTable("manufacturers", "r3e_content");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tracks_name");

                    b.ToTable("tracks", "r3e_content");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Car", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.R3EContent.CarClass", "Class")
                        .WithMany("Cars")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cars_car_classes");

                    b.HasOne("R3EServerRaceResult.Models.R3EContent.Manufacturer", "Manufacturer")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cars_manufacturers");

                    b.Navigation("Class");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Layout", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.R3EContent.Track", "Track")
                        .WithMany("Layouts")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layouts_tracks");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Livery", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.R3EContent.Car", "Car")
                        .WithMany("Liveries")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_liveries_cars");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Car", b =>
                {
                    b.Navigation("Liveries");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.CarClass", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Manufacturer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.R3EContent.Track", b =>
                {
                    b.Navigation("Layouts");
                });
#pragma warning restore 612, 618
        }
    }
}
