// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R3EServerRaceResult.Data;

#nullable disable

namespace R3EServerRaceResult.Migrations
{
    [DbContext(typeof(RaceStatsDbContext))]
    partial class RaceStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.Driver", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LayoutId")
                        .HasColumnType("integer");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("LayoutId");

                    b.HasIndex("TrackId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.Lap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<long?>("LapTime")
                        .HasColumnType("bigint");

                    b.Property<long?>("Sector1Time")
                        .HasColumnType("bigint");

                    b.Property<long?>("Sector2Time")
                        .HasColumnType("bigint");

                    b.Property<long?>("Sector3Time")
                        .HasColumnType("bigint");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LapTime");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "DriverId", "LapNumber");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("IncidentPoints")
                        .HasColumnType("integer");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InvolvedDriverId")
                        .HasColumnType("integer");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("IncidentType");

                    b.HasIndex("InvolvedDriverId");

                    b.HasIndex("SessionId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("BestLapTime")
                        .HasColumnType("bigint");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassPosition")
                        .HasColumnType("integer");

                    b.Property<int>("ClassStartPosition")
                        .HasColumnType("integer");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<string>("FinishStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("StartPosition")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLaps")
                        .HasColumnType("integer");

                    b.Property<long>("TotalRaceTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BestLapTime");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("Position");

                    b.HasIndex("SessionId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SessionType");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.Lap", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.RaceStats.Driver", "Driver")
                        .WithMany("Laps")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R3EServerRaceResult.Models.RaceStats.RaceSession", "Session")
                        .WithMany("Laps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceIncident", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.RaceStats.Driver", "Driver")
                        .WithMany("Incidents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R3EServerRaceResult.Models.RaceStats.Driver", "InvolvedDriver")
                        .WithMany("InvolvedIncidents")
                        .HasForeignKey("InvolvedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("R3EServerRaceResult.Models.RaceStats.RaceSession", "Session")
                        .WithMany("Incidents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("InvolvedDriver");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceResult", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.RaceStats.Driver", "Driver")
                        .WithMany("Results")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R3EServerRaceResult.Models.RaceStats.RaceSession", "Session")
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceSession", b =>
                {
                    b.HasOne("R3EServerRaceResult.Models.RaceStats.Event", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.Driver", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("InvolvedIncidents");

                    b.Navigation("Laps");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.Event", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("R3EServerRaceResult.Models.RaceStats.RaceSession", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Laps");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
